export interface iDives {
  id: number
  name: string
  date: any
  type: string
  maxDepth: number
  diveTime: number
  waterType: string
  waterTaste: string
  weather: string
  airTemperature: number
  surfaceTemperature: number
  deepTemperature: number
  visibility: string
  waves: string
  current: string
  suit: string
  ballast: number
  tank: string
  tankSize: number
  gasMix: string
  initialPressure: number
  finalPressure: number
  usedAir: number
  judgement: string
  notes: string
  buddy: string
  certified: boolean
}
